image: mono:5.14

stages:
    - build

build-tag:
    stage: build
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.nupkg
    script:
        - ./build.sh --target=push --key=$NUGET_API_KEY

build-ci:
    stage: build
    only:
        - master
    except:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_SHA}"
        expire_in: 4 weeks
        paths:
          - ./*.nupkg
    script:
        - ./build.sh
